'use strict';
// Builds dist/ - a self-contained static site you can drop on any free host.
//
//   node tools/build-static.js
//
// Output has no backend and no build step at the host: plain HTML, CSS and JS.
const fs = require('fs');
const path = require('path');
const { parseM3U } = require('./lib-m3u');
const { SOURCE_URL } = require('./source-url');

const ROOT = path.join(__dirname, '..');
const WEB = path.join(ROOT, 'web');
const DIST = path.join(ROOT, 'dist');
const SELECTION = path.join(ROOT, 'config', 'channels.txt');
const SITE_TITLE = process.env.SITE_TITLE || 'Live TV';

function readSelection() {
  if (!fs.existsSync(SELECTION)) return null;
  const names = [];
  for (const line of fs.readFileSync(SELECTION, 'utf8').split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    names.push(t);
  }
  return names;
}

async function main() {
  const selection = readSelection();
  if (!selection) {
    console.error('config/channels.txt is missing. Run:  npm run channels');
    process.exitCode = 1;
    return;
  }
  if (!selection.length) {
    console.error('config/channels.txt has no channels enabled - everything is commented out.');
    process.exitCode = 1;
    return;
  }

  process.stdout.write('Fetching playlist... ');
  const res = await fetch(SOURCE_URL, { redirect: 'follow' });
  if (!res.ok) throw new Error('HTTP ' + res.status);
  const all = parseM3U(await res.text());
  console.log(all.length + ' channels in source');

  const wanted = new Set(selection);
  const seen = new Set();
  const chosen = [];
  const dropped = { insecure: [], missing: [] };

  for (const c of all) {
    if (!wanted.has(c.name)) continue;
    if (seen.has(c.name)) continue;
    // A hosted site is https; browsers block plain-http video on it outright.
    if (!c.url.startsWith('https://')) {
      dropped.insecure.push(c.name);
      seen.add(c.name);
      continue;
    }
    seen.add(c.name);
    chosen.push(c);
  }

  for (const name of wanted) {
    if (!seen.has(name)) dropped.missing.push(name);
  }

  if (!chosen.length) {
    console.error('\nNothing to build: none of the selected channels are usable.');
    process.exitCode = 1;
    return;
  }

  // --- emit ---------------------------------------------------------------
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });

  const html = fs
    .readFileSync(path.join(WEB, 'index.html'), 'utf8')
    .split('__SITE_TITLE__').join(SITE_TITLE);
  fs.writeFileSync(path.join(DIST, 'index.html'), html);

  fs.copyFileSync(path.join(WEB, 'app.js'), path.join(DIST, 'app.js'));
  fs.copyFileSync(path.join(ROOT, 'public', 'style.css'), path.join(DIST, 'style.css'));

  // Vendored so the site has no external dependency at runtime.
  fs.copyFileSync(
    path.join(ROOT, 'node_modules', 'hls.js', 'dist', 'hls.min.js'),
    path.join(DIST, 'hls.min.js')
  );

  const channelsJs =
    '// Generated by tools/build-static.js - do not edit by hand.\n' +
    'window.SOURCE_URL = ' + JSON.stringify(SOURCE_URL) + ';\n' +
    'window.SELECTION = ' + JSON.stringify(chosen.map((c) => c.name)) + ';\n' +
    'window.SNAPSHOT = ' + JSON.stringify(chosen) + ';\n';
  fs.writeFileSync(path.join(DIST, 'channels.js'), channelsJs);

  // Stops hosts trying to run Jekyll or similar on the output.
  fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

  const groups = new Set(chosen.map((c) => c.group));
  const bytes = fs.readdirSync(DIST)
    .reduce((n, f) => n + fs.statSync(path.join(DIST, f)).size, 0);

  console.log('');
  console.log('Built dist/');
  console.log('  ' + chosen.length + ' channels across ' + groups.size + ' groups');
  console.log('  ' + (bytes / 1024).toFixed(0) + ' KB total');
  if (dropped.insecure.length) {
    console.log('  ' + dropped.insecure.length + ' dropped (http-only, blocked on https)');
  }
  if (dropped.missing.length) {
    console.log('  ' + dropped.missing.length + ' selected but no longer in the playlist:');
    for (const n of dropped.missing.slice(0, 8)) console.log('      - ' + n);
    if (dropped.missing.length > 8) {
      console.log('      ... and ' + (dropped.missing.length - 8) + ' more');
    }
  }
  console.log('');
  console.log('Preview locally :  npm run preview');
  console.log('Then upload the dist/ folder to any static host.');
}

main().catch((err) => {
  console.error('Build failed:', err.message);
  process.exitCode = 1;
});
