'use strict';
// Builds dist/ - a self-contained static site you can drop on any free host.
//
//   node tools/build-static.js
//
// Output has no backend and no build step at the host: plain HTML, CSS and JS.
const fs = require('fs');
const path = require('path');
const { fetchAndMerge, unplayableReason } = require('./lib-m3u');
const { classify, buildTree } = require('./categorize');
const { SOURCE_URLS } = require('./source-url');

const ROOT = path.join(__dirname, '..');
const WEB = path.join(ROOT, 'web');
const DIST = path.join(ROOT, 'dist');
const SELECTION = path.join(ROOT, 'config', 'channels.txt');
const SITE_TITLE = process.env.SITE_TITLE || 'SKFeath TV';

function readSelection() {
  if (!fs.existsSync(SELECTION)) return null;
  const names = [];
  for (const line of fs.readFileSync(SELECTION, 'utf8').split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    names.push(t);
  }
  return names;
}

async function main() {
  const selection = readSelection();
  if (!selection) {
    console.error('config/channels.txt is missing. Run:  npm run channels');
    process.exitCode = 1;
    return;
  }
  if (!selection.length) {
    console.error('config/channels.txt has no channels enabled - everything is commented out.');
    process.exitCode = 1;
    return;
  }

  console.log('Fetching ' + SOURCE_URLS.length + ' playlist(s)...');
  const { channels: all, sources } = await fetchAndMerge(SOURCE_URLS);
  for (const s of sources) {
    if (s.error) console.log('  FAILED  ' + s.url + '  (' + s.error + ')');
    else console.log('  ok      ' + s.url + '  -  ' + s.total + ' channels');
  }
  console.log(all.length + ' unique channels after merging');
  if (!all.length) throw new Error('No channels loaded from any source');

  const wanted = new Set(selection);
  const seen = new Set();
  const chosen = [];
  const dropped = { insecure: [], missing: [] };

  for (const c of all) {
    if (!wanted.has(c.name)) continue;
    if (seen.has(c.name)) continue;
    // Skip anything a browser cannot play: plain http on an https page,
    // YouTube/Twitch page links, DASH manifests.
    const reason = unplayableReason(c.url);
    if (reason) {
      dropped.insecure.push(c.name);
      seen.add(c.name);
      continue;
    }
    seen.add(c.name);
    // Reclassify off the source's country grouping into a usable taxonomy.
    chosen.push({ ...c, ...classify(c) });
  }

  for (const name of wanted) {
    if (!seen.has(name)) dropped.missing.push(name);
  }

  if (!chosen.length) {
    console.error('\nNothing to build: none of the selected channels are usable.');
    process.exitCode = 1;
    return;
  }

  // --- emit ---------------------------------------------------------------
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });

  const html = fs
    .readFileSync(path.join(WEB, 'index.html'), 'utf8')
    .split('__SITE_TITLE__').join(SITE_TITLE);
  fs.writeFileSync(path.join(DIST, 'index.html'), html);

  fs.copyFileSync(path.join(WEB, 'app.js'), path.join(DIST, 'app.js'));
  fs.copyFileSync(path.join(WEB, 'style.css'), path.join(DIST, 'style.css'));

  // Vendored so the site has no external dependency at runtime.
  fs.copyFileSync(
    path.join(ROOT, 'node_modules', 'hls.js', 'dist', 'hls.min.js'),
    path.join(DIST, 'hls.min.js')
  );

  const channelsJs =
    '// Generated by tools/build-static.js - do not edit by hand.\n' +
    'window.SOURCE_URLS = ' + JSON.stringify(SOURCE_URLS) + ';\n' +
    'window.SELECTION = ' + JSON.stringify(chosen.map((c) => c.name)) + ';\n' +
    'window.SNAPSHOT = ' + JSON.stringify(chosen) + ';\n' +
    'window.TREE = ' + JSON.stringify(buildTree(chosen)) + ';\n';
  fs.writeFileSync(path.join(DIST, 'channels.js'), channelsJs);

  // Stops hosts trying to run Jekyll or similar on the output.
  fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

  const groups = new Set(chosen.map((c) => c.category));
  const bytes = fs.readdirSync(DIST)
    .reduce((n, f) => n + fs.statSync(path.join(DIST, f)).size, 0);

  console.log('');
  console.log('Built dist/');
  const tree = buildTree(chosen);
  console.log('  ' + chosen.length + ' channels across ' + groups.size + ' categories');
  for (const t of tree) {
    console.log('      ' + String(t.total).padStart(5) + '  ' + t.category +
      '  (' + t.subcategories.length + ' sub)');
  }
  console.log('  ' + (bytes / 1024).toFixed(0) + ' KB total');
  if (dropped.insecure.length) {
    console.log('  ' + dropped.insecure.length + ' dropped (unplayable in a browser)');
  }
  if (dropped.missing.length) {
    console.log('  ' + dropped.missing.length + ' selected but no longer in the playlist:');
    for (const n of dropped.missing.slice(0, 8)) console.log('      - ' + n);
    if (dropped.missing.length > 8) {
      console.log('      ... and ' + (dropped.missing.length - 8) + ' more');
    }
  }
  console.log('');
  console.log('Preview locally :  npm run preview');
  console.log('Then upload the dist/ folder to any static host.');
}

main().catch((err) => {
  console.error('Build failed:', err.message);
  process.exitCode = 1;
});
